#!/usr/bin/env bash

echo "Usage: $0 reponame user private[true/false]"

name=$1
user=${2:-$USER}
private=${3:-true}
# get current dir
directory=$(pwd)
# change dir to this directory
exec_dir=$(dirname $(which gh_create_repo))
cd "$exec_dir"
# create repo with name passed as arg
docker-compose create create_repo --build
docker-compose run create_repo python main.py --user=$user --name=$name --private=$private
docker-compose down
cd "$directory"
# initialize git in directory if not present
if ! [[ -d .git ]]; then
    git init
fi
# set up remote origin if not present
if ! git remote -v | grep "github.com"; then
    git remote add origin git@github.com:$user/$name.git
fi
